### ISSUE TITLE
 -🎄- Day 01: Trebuchet -🎄-

### ISSUE THREAD

**Issue by eunice-hong** [plain-bagel/AoC-2023#6]
# Day 1:  

> 🥯 이 쓰레드에서 오늘의 퍼즐에 대해 이야기하세요!

💡 오늘의 문제를 해결했나요? 다른 베이글러들을 위해 팁을 전수해주세요.
❗️ 어려운 문제를 만났나요? 베이글러들에게 질문을 던져보세요.
🪄 이외에도 오늘 문제에 관한 이야기라면 자유롭게 이야기하세요.

**Comment by eunice-hong** [comment]
#8 저는 Kotlin 을 주 언어로 사용하고 있지만 올해는 dart 로 도전합니다! 💪

**Comment by renardyreveur** [comment]
#10 오랜만에 다시 써보는 하스켈로 예열하고 있습니다!! 별 2개 🌟 적립합니다!! 👍

**Comment by renardyreveur** [comment]
파트 1 문제를 신경망을 활용하여 푼 내용에 대한 간단한 글과 코드를  #28 에 추가해 보았습니다!

딥러닝에 관심이 있거나 JAX에 관심 있으신 분들 한번 확인해보세요!! ⚡
